version: "3.7"
services:
  db:
    image: postgres:15.2
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
